import "server-only";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { openai } from "@/lib/openai";
import { toFile } from "openai";

// Re-export shared constants so API routes can import from one place
export { DOC_TYPES, type DocTypeKey } from "@/lib/tools/voice-to-doc-shared";
import { DOC_TYPES, type DocTypeKey } from "@/lib/tools/voice-to-doc-shared";

export interface VoiceToDocResult {
  docType: DocTypeKey;
  label: string;
  transcript: string;
  formatted: string;
}

export async function generateVoiceDoc(
  audioBuffer: ArrayBuffer,
  mimeType: string,
  docType: DocTypeKey,
  filename: string
): Promise<ArrayBuffer> {
  // Transcribe with Whisper
  const audioFile = await toFile(Buffer.from(audioBuffer), filename, { type: mimeType });
  const transcription = await openai.audio.transcriptions.create({
    file: audioFile,
    model: "whisper-1",
  });

  const transcript = transcription.text;
  if (!transcript || !transcript.trim()) {
    throw new Error("No speech detected in the audio file.");
  }

  // Format with GPT-4o-mini using the doc type's system prompt
  const docConfig = DOC_TYPES[docType];
  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: docConfig.prompt },
      { role: "user", content: transcript },
    ],
  });

  const formatted = completion.choices[0]?.message?.content ?? "";

  return buildPdf(formatted, docType, docConfig.label, filename);
}

// ── PDF builder ─────────────────────────────────────────────────

async function buildPdf(
  text: string,
  docType: DocTypeKey,
  docLabel: string,
  originalFilename: string
): Promise<ArrayBuffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const W = 595; // A4 points
  const H = 842;
  const MARGIN = 50;
  const TEXT_W = W - MARGIN * 2;
  const FONT_SIZE = 10;
  const LINE_H = FONT_SIZE * 1.6;

  // Violet accent color: #7C3AED
  const VIOLET = rgb(0.486, 0.227, 0.929);
  const VIOLET_LIGHT = rgb(0.655, 0.545, 0.98);
  const INK = rgb(0.05, 0.05, 0.05);
  const MUTED = rgb(0.55, 0.55, 0.55);

  let page = pdfDoc.addPage([W, H]);
  let y = H - MARGIN;
  let isFirstPage = true;

  const newPage = () => {
    page = pdfDoc.addPage([W, H]);
    y = H - MARGIN;
  };

  const drawLine = (line: string, opts?: { size?: number; isBold?: boolean; color?: ReturnType<typeof rgb> }) => {
    const size = opts?.size ?? FONT_SIZE;
    const lineFont = opts?.isBold ? bold : font;
    const color = opts?.color ?? INK;
    const lh = size * 1.6;
    if (y < MARGIN + lh) newPage();
    if (line) {
      try {
        page.drawText(line, { x: MARGIN, y, size, font: lineFont, color });
      } catch {
        // skip unsupported glyphs
      }
    }
    y -= lh;
  };

  // Draw header on first page
  if (isFirstPage) {
    isFirstPage = false;

    // Violet accent bar
    page.drawRectangle({
      x: 0,
      y: H - 8,
      width: W,
      height: 8,
      color: VIOLET,
    });

    // Adjust y to below the bar
    y = H - MARGIN - 8;

    // Right-side label
    const rightLabel = `${docLabel}  ·  Generated by UpdatePDF`;
    try {
      const labelWidth = font.widthOfTextAtSize(rightLabel, 8);
      page.drawText(rightLabel, {
        x: W - MARGIN - labelWidth,
        y: y + 4,
        size: 8,
        font,
        color: VIOLET_LIGHT,
      });
    } catch {
      // skip if text doesn't fit
    }

    // Doc type label (large)
    page.drawText(docLabel, {
      x: MARGIN,
      y,
      size: 16,
      font: bold,
      color: VIOLET,
    });
    y -= 22;

    // Source filename
    page.drawText(`Source: ${originalFilename}`, {
      x: MARGIN,
      y,
      size: 8,
      font,
      color: MUTED,
    });
    y -= LINE_H * 1.5;

    // Divider line
    page.drawLine({
      start: { x: MARGIN, y },
      end: { x: W - MARGIN, y },
      thickness: 0.5,
      color: rgb(0.88, 0.88, 0.88),
    });
    y -= LINE_H;
  }

  // Render formatted text, handling markdown-like headers
  const paragraphs = text.split(/\n+/);
  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) {
      y -= LINE_H * 0.4;
      continue;
    }

    // H2 headers (## Heading)
    if (trimmed.startsWith("## ")) {
      const heading = trimmed.slice(3).replace(/\*\*/g, "");
      y -= LINE_H * 0.5; // extra space before heading
      const lines = wrapText(heading, TEXT_W, bold, 11);
      for (const line of lines) {
        drawLine(line, { size: 11, isBold: true, color: VIOLET });
      }
      y -= 2;
      // Underline
      page.drawLine({
        start: { x: MARGIN, y: y + LINE_H * 0.3 },
        end: { x: W - MARGIN, y: y + LINE_H * 0.3 },
        thickness: 0.5,
        color: rgb(0.88, 0.88, 0.92),
      });
      continue;
    }

    // H1 headers (# Heading)
    if (trimmed.startsWith("# ")) {
      const heading = trimmed.slice(2).replace(/\*\*/g, "");
      y -= LINE_H * 0.5;
      const lines = wrapText(heading, TEXT_W, bold, 13);
      for (const line of lines) {
        drawLine(line, { size: 13, isBold: true, color: VIOLET });
      }
      continue;
    }

    // Bullet points or checkboxes
    const isBullet = trimmed.startsWith("- ") || trimmed.startsWith("• ") || trimmed.startsWith("[ ] ") || trimmed.startsWith("[x] ");
    if (isBullet) {
      let bulletText = trimmed;
      let prefix = "• ";
      if (trimmed.startsWith("- ")) { bulletText = trimmed.slice(2); }
      else if (trimmed.startsWith("• ")) { bulletText = trimmed.slice(2); }
      else if (trimmed.startsWith("[ ] ")) { bulletText = trimmed.slice(4); prefix = "☐ "; }
      else if (trimmed.startsWith("[x] ")) { bulletText = trimmed.slice(4); prefix = "☑ "; }

      // Strip bold markers from bullet text
      bulletText = bulletText.replace(/\*\*(.*?)\*\*/g, "$1");

      const bulletIndent = MARGIN + 12;
      const bulletTextW = TEXT_W - 12;
      const wrappedLines = wrapText(bulletText, bulletTextW, font, FONT_SIZE);

      for (let i = 0; i < wrappedLines.length; i++) {
        if (y < MARGIN + LINE_H) newPage();
        if (i === 0) {
          try {
            page.drawText(prefix, { x: MARGIN, y, size: FONT_SIZE, font, color: VIOLET });
            page.drawText(wrappedLines[i], { x: bulletIndent, y, size: FONT_SIZE, font, color: INK });
          } catch { /* skip */ }
        } else {
          try {
            page.drawText(wrappedLines[i], { x: bulletIndent, y, size: FONT_SIZE, font, color: INK });
          } catch { /* skip */ }
        }
        y -= LINE_H;
      }
      continue;
    }

    // Regular paragraph — strip bold markers for rendering (bold not supported mid-line in pdf-lib)
    const cleanPara = trimmed.replace(/\*\*(.*?)\*\*/g, "$1");
    const lines = wrapText(cleanPara, TEXT_W, font, FONT_SIZE);
    for (const line of lines) {
      drawLine(line);
    }
    y -= LINE_H * 0.3; // paragraph gap
  }

  const bytes = await pdfDoc.save();
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
}

function wrapText(
  text: string,
  maxWidth: number,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  size: number
): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    let width = 0;
    try {
      width = font.widthOfTextAtSize(candidate, size);
    } catch {
      width = candidate.length * size * 0.5;
    }
    if (width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}
